baseURL: "https://www.pabloborowicz.com"
languageCode: "en-us"
theme: "casper"
title: "Pablo Borowicz"
copyright: "&copy; since 2018 — All rights reserved"

menu:
  main:
    -
      identifier: "home"
      name: "Home"
      url: "/"
      weight: 10
    -
      identifier: "about"
      name: "About me"
      url: "/about/"
      weight: 20
    -
      name: "GitHub"
      url: "https://github.com/eternoendless"
      weight: 30

params:
  googleAnalyticsUserID: "G-1Y6HWCZ6XJ"
  author: "Pablo Borowicz"
  authorBio: "I'm Pablo Borowicz, a veteran software developer and team leader, developing for the web for since 1998."
  authoravatar: "/images/profile.jpg"
  description: "Thoughts on software development"
  githubName: "eternoendless"
  linkedinName: "pabloborowicz"
  hideHugoSupport: true

disqusShortname: pabloborowicz

permalinks:
  post: "/:slug/"

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4