name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.154.5'
          extended: true

      - name: Clean public directory
        run: rm -rf ./src/public

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Europe/Paris

      - name: Build
        run: echo $(date) && cd src/ && hugo

      - name: Create a CNAME file which mapping to our custom domain
        run: cd src/ && echo 'www.pabloborowicz.com' > public/CNAME

      - name: Return to root directory
        run: cd ..

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
